-- Baseline schema.
--
-- This is the former db/src/main.sql reset script, frozen as the first migration.

CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(16) NOT NULL UNIQUE
);

CREATE TABLE userdata (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR(64) UNIQUE NOT NULL,
    password_hashed VARCHAR(128) NOT NULL,
    first_name VARCHAR(24),
    last_name VARCHAR(24),
    date_of_birth DATE,
    role_id INTEGER DEFAULT 1 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_userdata_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE muscle_group (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    body_region VARCHAR(16) CHECK (body_region IN ('UPPER', 'LOWER', 'CORE'))
);

CREATE TABLE exercise (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT,
    name VARCHAR(128) NOT NULL,
    exercise_type VARCHAR(16) NOT NULL CHECK (exercise_type IN ('STRENGTH', 'CARDIO', 'MOBILITY')),
    description VARCHAR(1000),
    instructions TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_exercise_owner FOREIGN KEY (owner_user_id) REFERENCES userdata(id)
);

CREATE TABLE exercise_musclegroup (
    exercise_id BIGINT NOT NULL,
    muscle_group_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL CHECK (role IN ('PRIMARY', 'SECONDARY')),
    CONSTRAINT pk_exercise_musclegroup PRIMARY KEY (exercise_id, muscle_group_id),
    CONSTRAINT fk_exercise_musclegroup_exercise FOREIGN KEY (exercise_id) REFERENCES exercise(id),
    CONSTRAINT fk_exercise_musclegroup_musclegroup FOREIGN KEY (muscle_group_id) REFERENCES muscle_group(id)
);

CREATE TABLE workout_plan (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    day_type VARCHAR(16) NOT NULL CHECK (day_type IN ('PUSH', 'PULL', 'LEGS', 'CUSTOM')),
    description VARCHAR(1000),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_workout_plan_user FOREIGN KEY (user_id) REFERENCES userdata(id)
);

CREATE TABLE workout_exercise (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL,
    target_sets INTEGER,
    target_reps_min INTEGER,
    target_reps_max INTEGER,
    target_rpe NUMERIC(3,1),
    target_rest_seconds INTEGER,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_workout_exercise_order UNIQUE (plan_id, order_index),
    CONSTRAINT fk_workout_exercise_plan FOREIGN KEY (plan_id) REFERENCES workout_plan(id),
    CONSTRAINT fk_workout_exercise_exercise FOREIGN KEY (exercise_id) REFERENCES exercise(id)
);

CREATE TABLE session_log (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    plan_id BIGINT,
    started_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'ABANDONED')),
    ended_at TIMESTAMPTZ,
    notes VARCHAR(1000),
    session_type VARCHAR(16) CHECK (session_type IN ('FULL', 'QUICK')),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_session_log_user FOREIGN KEY (user_id) REFERENCES userdata(id),
    CONSTRAINT fk_session_log_plan FOREIGN KEY (plan_id) REFERENCES workout_plan(id)
);

CREATE TABLE session_exercise (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    session_log_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('PLANNED', 'COMPLETED', 'SKIPPED')),
    notes VARCHAR(1000),
    target_sets_snapshot INTEGER,
    target_reps_min_snapshot INTEGER,
    target_reps_max_snapshot INTEGER,
    target_rpe_snapshot NUMERIC(3,1),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_session_exercise_order UNIQUE (session_log_id, order_index),
    CONSTRAINT fk_session_exercise_session FOREIGN KEY (session_log_id) REFERENCES session_log(id) ON DELETE CASCADE,
    CONSTRAINT fk_session_exercise_exercise FOREIGN KEY (exercise_id) REFERENCES exercise(id)
);

CREATE TABLE exercise_set (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    session_exercise_id BIGINT NOT NULL,
    set_number INTEGER NOT NULL,
    reps INTEGER,
    weight_kg NUMERIC(6,2),
    rpe NUMERIC(3,1),
    duration_seconds INTEGER,
    distance_meters NUMERIC(8,2),
    avg_heart_rate INTEGER,
    rest_seconds_after INTEGER,
    notes VARCHAR(1000),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_exercise_set_number UNIQUE (session_exercise_id, set_number),
    CONSTRAINT fk_exercise_set_session_exercise FOREIGN KEY (session_exercise_id) REFERENCES session_exercise(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- Constraints
-- ---------------------------------------------------------------------------

-- Exercise name uniqueness is per owner, not global, allowing every user to define their own variant of an existing name.
CREATE UNIQUE INDEX uq_exercise_name ON exercise (owner_user_id, name) NULLS NOT DISTINCT WHERE deleted_at IS NULL;

-- At most one running session per user
CREATE UNIQUE INDEX uq_session_log_active ON session_log (user_id) WHERE status = 'IN_PROGRESS';
