-- Baseline schema.
--
-- This is the former db/src/main.sql reset script.
-- Account roles (USER, ADMIN)
CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(16) NOT NULL UNIQUE
);

-- User accounts
CREATE TABLE userdata (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR(64) UNIQUE NOT NULL,
    password_hashed VARCHAR(128) NOT NULL,
    role_id INTEGER DEFAULT 1 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_userdata_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- Lookup of muscle groups in two levels: groups (Chest, Back, ..., with body_region) and their areas (Upper Chest, Lats, ...).
CREATE TABLE muscle_group (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name VARCHAR(64) NOT NULL UNIQUE,
    body_region VARCHAR(16) CHECK (body_region IN ('UPPER', 'LOWER', 'CORE')),
    CONSTRAINT ck_muscle_group_region_on_top_level CHECK ((parent_id IS NULL) = (body_region IS NOT NULL)),
    CONSTRAINT fk_muscle_group_parent FOREIGN KEY (parent_id) REFERENCES muscle_group(id)
);

-- Global catalog (owner_user_id NULL, has a slug) and custom exercises of users (soft deleted)
CREATE TABLE exercise (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT,
    slug VARCHAR(128) UNIQUE,
    name VARCHAR(128) NOT NULL,
    exercise_type VARCHAR(16) NOT NULL CHECK (exercise_type IN ('STRENGTH', 'CARDIO', 'MOBILITY')),
    tracking_type VARCHAR(24) NOT NULL CHECK (tracking_type IN ('WEIGHT_REPS', 'BODYWEIGHT_REPS', 'ASSISTED_REPS', 'DURATION', 'WEIGHT_DISTANCE', 'DISTANCE_DURATION')),
    description VARCHAR(1000),
    instructions TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_exercise_slug_only_global CHECK ((owner_user_id IS NULL) = (slug IS NOT NULL)),
    CONSTRAINT fk_exercise_owner FOREIGN KEY (owner_user_id) REFERENCES userdata(id) ON DELETE CASCADE
);

-- Which muscle groups an exercise trains, primary or secondary (N:M-Table)
CREATE TABLE exercise_musclegroup (
    exercise_id BIGINT NOT NULL,
    muscle_group_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL CHECK (role IN ('PRIMARY', 'SECONDARY')),
    CONSTRAINT pk_exercise_musclegroup PRIMARY KEY (exercise_id, muscle_group_id),
    CONSTRAINT fk_exercise_musclegroup_exercise FOREIGN KEY (exercise_id) REFERENCES exercise(id) ON DELETE CASCADE,
    CONSTRAINT fk_exercise_musclegroup_musclegroup FOREIGN KEY (muscle_group_id) REFERENCES muscle_group(id)
);

-- Template for one training day. Presets have user_id NULL and a slug, users get copies (hard deleted)
CREATE TABLE routine (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    slug VARCHAR(128) UNIQUE,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(1000),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_routine_slug_only_preset CHECK ((user_id IS NULL) = (slug IS NOT NULL)),
    CONSTRAINT uq_routine_user_id UNIQUE (user_id, id),
    CONSTRAINT fk_routine_user FOREIGN KEY (user_id) REFERENCES userdata(id) ON DELETE CASCADE
);

-- Exercises of a routine with their targets for each exercise
CREATE TABLE routine_exercise (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    routine_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL CHECK (order_index >= 0),
    target_sets INTEGER CHECK (target_sets > 0),
    target_reps_min INTEGER CHECK (target_reps_min > 0),
    target_reps_max INTEGER CHECK (target_reps_max > 0),
    target_rpe NUMERIC(3,1) CHECK (target_rpe BETWEEN 1 AND 10),
    target_duration_seconds INTEGER CHECK (target_duration_seconds > 0),
    target_distance_meters NUMERIC(8,2) CHECK (target_distance_meters > 0),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_routine_exercise_reps_range CHECK (target_reps_min <= target_reps_max),
    CONSTRAINT uq_routine_exercise_order UNIQUE (routine_id, order_index) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk_routine_exercise_routine FOREIGN KEY (routine_id) REFERENCES routine(id) ON DELETE CASCADE,
    CONSTRAINT fk_routine_exercise_exercise FOREIGN KEY (exercise_id) REFERENCES exercise(id) DEFERRABLE
);

-- Ordered sequence of routines and rest days. Presets have user_id NULL and a slug, users get copies. Max three per user (service), one active.
CREATE TABLE program (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    slug VARCHAR(128) UNIQUE,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(1000),
    is_active BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_program_slug_only_preset CHECK ((user_id IS NULL) = (slug IS NOT NULL)),
    CONSTRAINT ck_program_preset_inactive CHECK (user_id IS NOT NULL OR NOT is_active),
    CONSTRAINT uq_program_user_id UNIQUE (user_id, id),
    CONSTRAINT fk_program_user FOREIGN KEY (user_id) REFERENCES userdata(id) ON DELETE CASCADE
);

-- One slot of a program: a routine, or a rest day when routine_id is NULL. Slots of preset programs (user_id NULL) only reference presets, maintained by migrations.
CREATE TABLE program_day (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    program_id BIGINT NOT NULL,
    routine_id BIGINT,
    order_index INTEGER NOT NULL CHECK (order_index >= 0),
    CONSTRAINT uq_program_day_user_id UNIQUE (user_id, id),
    CONSTRAINT uq_program_day_order UNIQUE (program_id, order_index) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk_program_day_program_id FOREIGN KEY (program_id) REFERENCES program(id) ON DELETE CASCADE,
    CONSTRAINT fk_program_day_routine_id FOREIGN KEY (routine_id) REFERENCES routine(id) ON DELETE SET NULL,
    CONSTRAINT fk_program_day_program FOREIGN KEY (user_id, program_id) REFERENCES program(user_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_program_day_routine FOREIGN KEY (user_id, routine_id) REFERENCES routine(user_id, id) ON DELETE SET NULL (routine_id)
);

-- A performed training. Copies what it needs from its routine at the start
CREATE TABLE workout (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    routine_id BIGINT,
    program_day_id BIGINT,
    name VARCHAR(128) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    ended_at TIMESTAMPTZ,
    notes VARCHAR(1000),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_workout_ended_after_start CHECK (ended_at IS NULL OR ended_at >= started_at),
    CONSTRAINT fk_workout_user FOREIGN KEY (user_id) REFERENCES userdata(id) ON DELETE CASCADE,
    CONSTRAINT fk_workout_routine FOREIGN KEY (user_id, routine_id) REFERENCES routine(user_id, id) ON DELETE SET NULL (routine_id),
    CONSTRAINT fk_workout_program_day FOREIGN KEY (user_id, program_day_id) REFERENCES program_day(user_id, id) ON DELETE SET NULL (program_day_id)
);

-- Exercise performed in a workout, with snapshots of the routine targets. Done once it has sets.
CREATE TABLE workout_exercise (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    workout_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL CHECK (order_index >= 0),
    notes VARCHAR(1000),
    target_sets_snapshot INTEGER,
    target_reps_min_snapshot INTEGER,
    target_reps_max_snapshot INTEGER,
    target_rpe_snapshot NUMERIC(3,1),
    target_duration_seconds_snapshot INTEGER,
    target_distance_meters_snapshot NUMERIC(8,2),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_workout_exercise_order UNIQUE (workout_id, order_index) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk_workout_exercise_workout FOREIGN KEY (workout_id) REFERENCES workout(id) ON DELETE CASCADE,
    CONSTRAINT fk_workout_exercise_exercise FOREIGN KEY (exercise_id) REFERENCES exercise(id) DEFERRABLE
);

-- One logged set. Which values are filled depends on exercise.tracking_type.
CREATE TABLE workout_set (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    workout_exercise_id BIGINT NOT NULL,
    set_number INTEGER NOT NULL,
    set_type VARCHAR(16) DEFAULT 'WORKING' NOT NULL CHECK (set_type IN ('WARMUP', 'WORKING', 'DROP')),
    reps INTEGER CHECK (reps >= 0),
    weight_kg NUMERIC(6,2) CHECK (weight_kg >= 0),
    rpe NUMERIC(3,1) CHECK (rpe BETWEEN 1 AND 10),
    duration_seconds INTEGER CHECK (duration_seconds > 0),
    distance_meters NUMERIC(8,2) CHECK (distance_meters >= 0),
    notes VARCHAR(1000),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_workout_set_number UNIQUE (workout_exercise_id, set_number) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk_workout_set_workout_exercise FOREIGN KEY (workout_exercise_id) REFERENCES workout_exercise(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- Constraints
-- ---------------------------------------------------------------------------

-- Exercise name uniqueness is per owner, not global, allowing every user to define their own variant of an existing name.
CREATE UNIQUE INDEX uq_exercise_name ON exercise (owner_user_id, name) NULLS NOT DISTINCT WHERE deleted_at IS NULL;

-- At most one running workout per user
CREATE UNIQUE INDEX uq_workout_active ON workout (user_id) WHERE status = 'IN_PROGRESS';

-- At most one active program per user. The limit of three programs per user is checked by the service.
CREATE UNIQUE INDEX uq_program_active ON program (user_id) WHERE is_active;

-- Deleting a user cascades to everything they own. The DEFERRABLE references between owned rows
-- (routine and workout to own exercise) are checked too early otherwise. A deleted routine only
-- clears the reference of its workouts, they copied everything they need at their start, and turns
-- its program slots into rest days (routine_id NULL). Preset routines (user_id NULL) cannot be
-- referenced by programs or workouts at all, the composite keys require the same user, so presets are copied.
-- The order constraints are deferred to commit, because reordering updates one row at a time.
