-- Baseline schema.
--
-- This is the former db/src/main.sql reset script, frozen as the first migration.

CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(16) NOT NULL UNIQUE
);

CREATE TABLE userdata (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR(64) UNIQUE NOT NULL,
    password_hashed VARCHAR(128) NOT NULL,
    role_id INTEGER DEFAULT 1 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_userdata_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE muscle_group (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    body_region VARCHAR(16) CHECK (body_region IN ('UPPER', 'LOWER', 'CORE'))
);

CREATE TABLE exercise (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT,
    slug VARCHAR(128) UNIQUE,
    name VARCHAR(128) NOT NULL,
    exercise_type VARCHAR(16) NOT NULL CHECK (exercise_type IN ('STRENGTH', 'CARDIO', 'MOBILITY')),
    tracking_type VARCHAR(24) NOT NULL CHECK (tracking_type IN ('WEIGHT_REPS', 'BODYWEIGHT_REPS', 'ASSISTED_REPS', 'DURATION', 'WEIGHT_DISTANCE', 'DISTANCE_DURATION')),
    description VARCHAR(1000),
    instructions TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_exercise_slug_only_global CHECK ((owner_user_id IS NULL) = (slug IS NOT NULL)),
    CONSTRAINT fk_exercise_owner FOREIGN KEY (owner_user_id) REFERENCES userdata(id) ON DELETE CASCADE
);

CREATE TABLE exercise_musclegroup (
    exercise_id BIGINT NOT NULL,
    muscle_group_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL CHECK (role IN ('PRIMARY', 'SECONDARY')),
    CONSTRAINT pk_exercise_musclegroup PRIMARY KEY (exercise_id, muscle_group_id),
    CONSTRAINT fk_exercise_musclegroup_exercise FOREIGN KEY (exercise_id) REFERENCES exercise(id) ON DELETE CASCADE,
    CONSTRAINT fk_exercise_musclegroup_musclegroup FOREIGN KEY (muscle_group_id) REFERENCES muscle_group(id)
);

CREATE TABLE routine (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(1000),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_routine_user_id UNIQUE (user_id, id),
    CONSTRAINT fk_routine_user FOREIGN KEY (user_id) REFERENCES userdata(id) ON DELETE CASCADE
);

CREATE TABLE routine_exercise (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    routine_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL CHECK (order_index >= 0),
    target_sets INTEGER CHECK (target_sets > 0),
    target_reps_min INTEGER CHECK (target_reps_min > 0),
    target_reps_max INTEGER CHECK (target_reps_max > 0),
    target_rpe NUMERIC(3,1) CHECK (target_rpe BETWEEN 1 AND 10),
    target_duration_seconds INTEGER CHECK (target_duration_seconds > 0),
    target_distance_meters NUMERIC(8,2) CHECK (target_distance_meters > 0),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_routine_exercise_reps_range CHECK (target_reps_min <= target_reps_max),
    CONSTRAINT uq_routine_exercise_order UNIQUE (routine_id, order_index) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk_routine_exercise_routine FOREIGN KEY (routine_id) REFERENCES routine(id) ON DELETE CASCADE,
    CONSTRAINT fk_routine_exercise_exercise FOREIGN KEY (exercise_id) REFERENCES exercise(id) DEFERRABLE
);

CREATE TABLE workout (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    routine_id BIGINT,
    name VARCHAR(128) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    ended_at TIMESTAMPTZ,
    notes VARCHAR(1000),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_workout_ended_after_start CHECK (ended_at IS NULL OR ended_at >= started_at),
    CONSTRAINT fk_workout_user FOREIGN KEY (user_id) REFERENCES userdata(id) ON DELETE CASCADE,
    CONSTRAINT fk_workout_routine FOREIGN KEY (user_id, routine_id) REFERENCES routine(user_id, id) ON DELETE SET NULL (routine_id)
);

CREATE TABLE workout_exercise (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    workout_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL CHECK (order_index >= 0),
    notes VARCHAR(1000),
    target_sets_snapshot INTEGER,
    target_reps_min_snapshot INTEGER,
    target_reps_max_snapshot INTEGER,
    target_rpe_snapshot NUMERIC(3,1),
    target_duration_seconds_snapshot INTEGER,
    target_distance_meters_snapshot NUMERIC(8,2),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_workout_exercise_order UNIQUE (workout_id, order_index) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk_workout_exercise_workout FOREIGN KEY (workout_id) REFERENCES workout(id) ON DELETE CASCADE,
    CONSTRAINT fk_workout_exercise_exercise FOREIGN KEY (exercise_id) REFERENCES exercise(id) DEFERRABLE
);

CREATE TABLE workout_set (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    workout_exercise_id BIGINT NOT NULL,
    set_number INTEGER NOT NULL,
    set_type VARCHAR(16) DEFAULT 'WORKING' NOT NULL CHECK (set_type IN ('WARMUP', 'WORKING', 'DROP')),
    reps INTEGER CHECK (reps >= 0),
    weight_kg NUMERIC(6,2) CHECK (weight_kg >= 0),
    rpe NUMERIC(3,1) CHECK (rpe BETWEEN 1 AND 10),
    duration_seconds INTEGER CHECK (duration_seconds > 0),
    distance_meters NUMERIC(8,2) CHECK (distance_meters >= 0),
    notes VARCHAR(1000),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_workout_set_number UNIQUE (workout_exercise_id, set_number) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk_workout_set_workout_exercise FOREIGN KEY (workout_exercise_id) REFERENCES workout_exercise(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- Constraints
-- ---------------------------------------------------------------------------

-- Exercise name uniqueness is per owner, not global, allowing every user to define their own variant of an existing name.
CREATE UNIQUE INDEX uq_exercise_name ON exercise (owner_user_id, name) NULLS NOT DISTINCT WHERE deleted_at IS NULL;

-- At most one running workout per user
CREATE UNIQUE INDEX uq_workout_active ON workout (user_id) WHERE status = 'IN_PROGRESS';

-- Deleting a user cascades to everything they own. The DEFERRABLE references between owned rows
-- (routine and workout to own exercise) are checked too early otherwise. A deleted routine only
-- clears the reference of its workouts, they copied everything they need at their start.
-- The order constraints are deferred to commit, because reordering updates one row at a time.
