DROP TABLE exercise_set CASCADE CONSTRAINTS;
DROP TABLE session_exercise CASCADE CONSTRAINTS;
DROP TABLE session_log CASCADE CONSTRAINTS;
DROP TABLE workout_exercise CASCADE CONSTRAINTS;
DROP TABLE workout_plan CASCADE CONSTRAINTS;
DROP TABLE exercise_musclegroup CASCADE CONSTRAINTS;
DROP TABLE exercise CASCADE CONSTRAINTS;
DROP TABLE muscle_group CASCADE CONSTRAINTS;
DROP TABLE userdata CASCADE CONSTRAINTS;
DROP TABLE roles CASCADE CONSTRAINTS;

CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(16) NOT NULL UNIQUE
);

CREATE TABLE userdata (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR2(32) UNIQUE NOT NULL,
    email VARCHAR2(64) UNIQUE NOT NULL,
    password_hashed VARCHAR2(128) NOT NULL,
    first_name VARCHAR2(24),
    last_name VARCHAR2(24),
    date_of_birth DATE NOT NULL,
    role_id NUMBER DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_userdata_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE muscle_group (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR2(64) NOT NULL UNIQUE,
    body_region VARCHAR2(16) CHECK (body_region IN ('UPPER', 'LOWER', 'CORE'))
);

CREATE TABLE exercise (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    owner_user_id NUMBER,
    name VARCHAR2(128) NOT NULL,
    exercise_type VARCHAR2(16) NOT NULL CHECK (exercise_type IN ('STRENGTH', 'CARDIO', 'MOBILITY')),
    description VARCHAR2(1000),
    instructions CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_exercise_owner FOREIGN KEY (owner_user_id) REFERENCES userdata(id)
);

CREATE TABLE exercise_musclegroup (
    exercise_id NUMBER NOT NULL,
    muscle_group_id NUMBER NOT NULL,
    role VARCHAR2(16) NOT NULL CHECK (role IN ('PRIMARY', 'SECONDARY')),
    CONSTRAINT pk_exercise_musclegroup PRIMARY KEY (exercise_id, muscle_group_id),
    CONSTRAINT fk_exercise_musclegroup_exercise FOREIGN KEY (exercise_id) REFERENCES exercise(id),
    CONSTRAINT fk_exercise_musclegroup_musclegroup FOREIGN KEY (muscle_group_id) REFERENCES muscle_group(id)
);

CREATE TABLE workout_plan (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(128) NOT NULL,
    day_type VARCHAR2(16) NOT NULL CHECK (day_type IN ('PUSH', 'PULL', 'LEGS', 'CUSTOM')),
    description VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_workout_plan_user FOREIGN KEY (user_id) REFERENCES userdata(id)
);

CREATE TABLE workout_exercise (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    plan_id NUMBER NOT NULL,
    exercise_id NUMBER NOT NULL,
    order_index NUMBER NOT NULL,
    target_sets NUMBER,
    target_reps_min NUMBER,
    target_reps_max NUMBER,
    target_rpe NUMBER(3,1),
    target_rest_seconds NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_workout_exercise_order UNIQUE (plan_id, order_index),
    CONSTRAINT fk_workout_exercise_plan FOREIGN KEY (plan_id) REFERENCES workout_plan(id),
    CONSTRAINT fk_workout_exercise_exercise FOREIGN KEY (exercise_id) REFERENCES exercise(id)
);

CREATE TABLE session_log (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    plan_id NUMBER,
    started_at TIMESTAMP NOT NULL,
    status VARCHAR2(16) NOT NULL CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'ABANDONED')),
    ended_at TIMESTAMP,
    notes VARCHAR2(1000),
    session_type VARCHAR2(16) CHECK (session_type IN ('FULL', 'QUICK')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_session_log_user FOREIGN KEY (user_id) REFERENCES userdata(id),
    CONSTRAINT fk_session_log_plan FOREIGN KEY (plan_id) REFERENCES workout_plan(id)
);

CREATE TABLE session_exercise (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    session_log_id NUMBER NOT NULL,
    exercise_id NUMBER NOT NULL,
    order_index NUMBER NOT NULL,
    status VARCHAR2(16) NOT NULL CHECK (status IN ('PLANNED', 'COMPLETED', 'SKIPPED')),
    notes VARCHAR2(1000),
    target_sets_snapshot NUMBER,
    target_reps_min_snapshot NUMBER,
    target_reps_max_snapshot NUMBER,
    target_rpe_snapshot NUMBER(3,1),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_session_exercise_order UNIQUE (session_log_id, order_index),
    CONSTRAINT fk_session_exercise_session FOREIGN KEY (session_log_id) REFERENCES session_log(id),
    CONSTRAINT fk_session_exercise_exercise FOREIGN KEY (exercise_id) REFERENCES exercise(id)
);

CREATE TABLE exercise_set (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    session_exercise_id NUMBER NOT NULL,
    set_number NUMBER NOT NULL,
    reps NUMBER,
    weight_kg NUMBER(6,2),
    rpe NUMBER(3,1),
    duration_seconds NUMBER,
    distance_meters NUMBER(8,2),
    avg_heart_rate NUMBER,
    rest_seconds_after NUMBER,
    notes VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_exercise_set_number UNIQUE (session_exercise_id, set_number),
    CONSTRAINT fk_exercise_set_session_exercise FOREIGN KEY (session_exercise_id) REFERENCES session_exercise(id)
);

INSERT INTO ROLES (name) VALUES ('USER');
INSERT INTO ROLES (id, name) VALUES (0, 'ADMIN');

INSERT INTO USERDATA (username, email, password_hashed, first_name, last_name, date_of_birth) VALUES ('Testuser 1', 'test@test', 'hash1', 'ab', 'cd', TO_DATE('01.01.2010', 'DD.MM.YYYY'));
INSERT INTO USERDATA (username, email, password_hashed, first_name, last_name, date_of_birth) VALUES ('Testuser 2', '2@test', 'hash2', 'ab2', 'cd2', TO_DATE('02.02.2020', 'DD.MM.YYYY'));

COMMIT;
