DROP TABLE userdata cascade constraints;
DROP TABLE roles cascade constraints;

CREATE TABLE roles (
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR2(16) NOT NULL UNIQUE
);

CREATE TABLE userdata (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR2(32) UNIQUE NOT NULL,
    email VARCHAR2(64) UNIQUE NOT NULL,
    password_hashed VARCHAR2(128) NOT NULL,
    first_name VARCHAR2(24),
    last_name VARCHAR2(24),
    date_of_birth DATE NOT NULL,
    role_id NUMBER DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_userdata_role FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

INSERT INTO ROLES (role_name) VALUES ('USER');
INSERT INTO ROLES (role_id, role_name) VALUES (0, 'ADMIN');

INSERT INTO USERDATA (username, email, password_hashed, first_name, last_name, date_of_birth) VALUES ('Testuser 1', 'test@test', 'hash1', 'ab', 'cd', TO_DATE('01.01.2010', 'DD.MM.YYYY'));
INSERT INTO USERDATA (username, email, password_hashed, first_name, last_name, date_of_birth) VALUES ('Testuser 2', '2@test', 'hash2', 'ab2', 'cd2', TO_DATE('02.02.2020', 'DD.MM.YYYY'));

COMMIT;